// Mock data for development and testing
import type {
  Client,
  Product,
  Truck,
  Order,
  Delivery,
  Destination,
  User,
  Driver,
} from "./types";

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Constructora ABC S.A. de C.V.",
    rif: "CABC850101ABC",
    address: "Av. Construcción 123, Ciudad",
    phone: "555-0101",
    email: "contacto@abc.com",
    is_active: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Materiales del Norte",
    rif: "MDN900202DEF",
    address: "Calle Norte 456, Ciudad",
    phone: "555-0202",
    email: "ventas@norte.com",
    is_active: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Obras y Proyectos",
    rif: "OYP950303GHI",
    address: "Blvd. Proyectos 789, Ciudad",
    phone: "555-0303",
    email: "info@obras.com",
    is_active: true,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    refProveedor: "ARE-001",
    name: "Arena",
    description: "Arena de río para construcción",
    is_active: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    refProveedor: "GRA-001",
    name: "Grava",
    description: 'Grava triturada 3/4"',
    is_active: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    refProveedor: "PIE-001",
    name: "Piedra",
    description: "Piedra braza para construcción",
    is_active: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    refProveedor: "TEP-001",
    name: "Tepetate",
    description: "Tepetate para relleno",
    is_active: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
];

export const mockTrucks: Truck[] = [
  {
    id: "1",
    placa: "ABC-123-D",
    brand: "Kenworth",
    model: "T800",
    capacity: 15.0,
    is_active: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "2",
    placa: "DEF-456-G",
    brand: "Freightliner",
    model: "Cascadia",
    capacity: 18.0,
    is_active: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "3",
    placa: "GHI-789-J",
    brand: "Volvo",
    model: "VNL",
    capacity: 20.0,
    is_active: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "4",
    placa: "JKL-012-M",
    brand: "Mack",
    model: "Anthem",
    capacity: 16.0,
    is_active: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
];

export const mockDestinations: Destination[] = [
  {
    id: "1",
    customer_id: "1",
    name: "Obra Av. Norte",
    direccion: "Av. Norte, Caracas",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    customer_id: "1",
    name: "Proyecto Residencial",
    direccion: "Urb. Los Palos Grandes",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    customer_id: "2",
    name: "Puente Autopista",
    direccion: "Autopista Regional",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    email: "cajero@cantera.com",
    name: "María González",
    role: "CASHIER",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    email: "patio@cantera.com",
    name: "Juan Pérez",
    role: "YARD",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    email: "seguridad@cantera.com",
    name: "Carlos López",
    role: "SECURITY",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    email: "admin@cantera.com",
    name: "Ana Martínez",
    role: "ADMIN",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    email: "reportes@cantera.com",
    name: "Luis Rodríguez",
    role: "REPORTS",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-2024-001",
    customer_id: "1",
    client: mockClients[0],
    estado: "CREADA",
    total: 2500.0,
    notes: "Entrega urgente",
    createdBy: "1",
    createdAt: new Date("2024-01-30T09:00:00"),
    updatedAt: new Date("2024-01-30T09:00:00"),
  },
  {
    id: "2",
    orderNumber: "ORD-2024-002",
    customer_id: "2",
    client: mockClients[1],
    estado: "EN_DESPACHO",
    total: 4500.0,
    notes: "",
    createdBy: "1",
    createdAt: new Date("2024-01-30T10:30:00"),
    updatedAt: new Date("2024-01-30T11:00:00"),
  },
];

export const mockDrivers: Driver[] = [
  {
    id: "1",
    name: "Juan Pérez",
    docId: "V-12345678",
    phone: "+58-414-1234567",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Carlos Rodriguez",
    docId: "V-87654321",
    phone: "+58-412-7654321",
    is_active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockDeliveries: Delivery[] = [
  {
    id: "1",
    orderId: "1",
    order: mockOrders[0],
    truckId: "1",
    truck: mockTrucks[0],
    cantidadBase: 10,
    estado: "ASIGNADA",
    createdAt: new Date("2024-01-30T09:00:00"),
    updatedAt: new Date("2024-01-30T09:00:00"),
  },
  {
    id: "2",
    orderId: "2",
    order: mockOrders[1],
    truckId: "2",
    truck: mockTrucks[1],
    cantidadBase: 15,
    loadedBy: "2",
    loadedAt: new Date("2024-01-30T11:00:00"),
    estado: "CARGADA",
    notes: "Carga completa",
    createdAt: new Date("2024-01-30T10:30:00"),
    updatedAt: new Date("2024-01-30T11:00:00"),
  },
];
